# Imports

In [47]:
import pandas as pd
import json
import requests
import numpy as np

# Question 1

In [48]:
response = requests.get("https://raw.githubusercontent.com/Papagoat/brain-assessment/main/restaurant_data.json")
if response.ok:
    json_data = response.json()
else: 
    print("No response detected")

In [49]:
json_df = pd.json_normalize(json_data)
json_df.head()

,results_found,results_start,results_shown,restaurants
0,29287,1,20,"[{'restaurant': {'R': {'res_id': 18649486}, 'a..."
1,7625,1,20,"[{'restaurant': {'R': {'res_id': 18707652}, 'a..."
2,21776,1,20,"[{'restaurant': {'R': {'res_id': 18392725}, 'a..."
3,16762,1,20,"[{'restaurant': {'R': {'res_id': 58882}, 'apik..."
4,12026,1,20,"[{'restaurant': {'R': {'res_id': 18893197}, 'a..."

In [50]:
# View Sample restaurant data
json_df.restaurants.iloc[0]

[{'restaurant': {'R': {'res_id': 18649486},
   'apikey': 'cba15beb4c265876a9828f242b4cf41c',
   'id': '18649486',
   'name': 'The Drunken Botanist',
   'url': 'https://www.zomato.com/ncr/the-drunken-botanist-dlf-cyber-city-gurgaon?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
   'location': {'address': 'Unit 1B & 1C, Upper Ground Floor-C, Building 10C, Cyber Hub, DLF Cyber City, Gurgaon',
    'locality': 'Cyber Hub, DLF Cyber City',
    'city': 'Gurgaon',
    'city_id': 1,
    'latitude': '28.4936741035',
    'longitude': '77.0883342996',
    'zipcode': '',
    'country_id': 1,
    'locality_verbose': 'Cyber Hub, DLF Cyber City, Gurgaon'},
   'switch_to_order_menu': 0,
   'cuisines': 'Continental, Italian, North Indian, Chinese',
   'average_cost_for_two': 1500,
   'price_range': 3,
   'currency': 'Rs.',
   'offers': [],
   'zomato_events': [{'event': {'event_id': 322331,
      'friendly_start_date': '06 March',
      'friendly_end_date': '28 August',
      'friendly_timing_str': 'Wednesday, 6th March - Wednesday, 28th August',
      'start_date': '2019-03-06',
      'end_date': '2019-08-28',
      'end_time': '23:59:59',
      'start_time': '20:00:00',
      'is_active': 1,
      'date_added': '2019-03-06 11:41:21',
      'photos': [{'photo': {'url': 'https://b.zmtcdn.com/data/zomato_events/photos/5a1/ac34cf3c271c9052e9d248c243df65a1_1551852711.jpg',
         'thumb_url': 'https://b.zmtcdn.com/data/zomato_events/photos/5a1/ac34cf3c271c9052e9d248c243df65a1_1551852711.jpg?fit=around%7C100%3A100&crop=100%3A100%3B%2A%2C%2A',
         'order': 0,
         'md5sum': 'ac34cf3c271c9052e9d248c243df65a1',
         'id': 434436,
         'photo_id': 434436,
         'uuid': 52695233531,
         'type': 'FEATURED'}}],
      'restaurants': [],
      'is_valid': 1,
      'share_url': 'http://www.zoma.to/r/0',
      'show_share_url': 0,
      'title': 'BackToBasic Wednesdays !!\n\n\n',
      'description': 'https://www.facebook.com/events/347477306085841/?ti=cl\n\nThe twilight and timbre, the delicious drinks and vibrant crowd. Are you ready to make Wednesdays awesome again with Rock Nights & sensational new Bands every week? Then you know where to find me! \n\nAlways High, Always Rocking only at TDB.',
      'display_time': '08:00 pm onwards',
      'display_date': '06 March - 28 August',
      'is_end_time_set': 0,
      'disclaimer': 'Restaurants are solely responsible for the service; availability and quality of the events including all or any cancellations/ modifications/ complaints.',
      'event_category': 1,
      'event_category_name': '',
      'book_link': '',
      'types': [],
      'share_data': {'should_show': 0}}}],
   'opentable_support': 0,
   'is_zomato_book_res': 0,
   'mezzo_provider': 'OTHER',
   'is_book_form_web_view': 0,
   'book_form_web_view_url': '',
   'book_again_url': '',
   'thumb': 'https://b.zmtcdn.com/data/pictures/6/18649486/891f5711b0028057cdf834ca1fee9780.jpg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A',
   'user_rating': {'aggregate_rating': '4.4',
    'rating_text': 'Very Good',
    'rating_color': '5BA829',
    'votes': '4765',
    'has_fake_reviews': 0},
   'photos_url': 'https://www.zomato.com/ncr/the-drunken-botanist-dlf-cyber-city-gurgaon/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop',
   'menu_url': 'https://www.zomato.com/ncr/the-drunken-botanist-dlf-cyber-city-gurgaon/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop',
   'featured_image': 'https://b.zmtcdn.com/data/pictures/6/18649486/891f5711b0028057cdf834ca1fee9780.jpg',
   'has_online_delivery': 0,
   'is_delivering_now': 0,
   'has_fake_reviews': 0,
   'include_bogo_offers': True,
   'deeplink': 'zomato://restaurant/18649486',
   'is_table_reservation_supported': 0,
   'has_table_booking': 0,
   'events_url': 'https://www.zomato.com/ncr/the-drunken-botanist-dlf-cyber-city-gurgaon/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
   'establishment_types': []}},
 {'restaurant': {'R': {'res_id': 308322},
   'apikey': 'cba15beb4c265876a9828f242b4cf41c',
   'id': '308322',
   'name': 'Hauz Khas Social',
   'url': 'https://www.zomato.com/HauzKhasSocial?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
   'location': {'address': '9-A & 12, Hauz Khas Village, New Delhi',
    'locality': 'Hauz Khas Village',
    'city': 'New Delhi',
    'city_id': 1,
    'latitude': '28.5542935327',
    'longitude': '77.1944381297',
    'zipcode': '',
    'country_id': 1,
    'locality_verbose': 'Hauz Khas Village, New Delhi'},
   'switch_to_order_menu': 0,
   'cuisines': 'Continental, American, Asian, North Indian, Chinese, Pizza, Biryani, Beverages',
   'average_cost_for_two': 1300,
   'price_range': 3,
   'currency': 'Rs.',
   'offers': [],
   'zomato_events': [{'event': {'event_id': 332812,
      'friendly_start_date': '29 March',
      'friendly_end_date': '23 May',
      'friendly_timing_str': 'Friday, 29th March - Thursday, 23rd May',
      'start_date': '2019-03-29',
      'end_date': '2019-05-23',
      'end_time': '01:35:00',
      'start_time': '09:00:00',
      'is_active': 1,
      'date_added': '2019-03-29 17:19:54',
      'photos': [{'photo': {'url': 'https://b.zmtcdn.com/data/zomato_events/photos/e11/de21c69b73b6220731a4191883338e11_1553860194.jpg',
         'thumb_url': 'https://b.zmtcdn.com/data/zomato_events/photos/e11/de21c69b73b6220731a4191883338e11_1553860194.jpg?fit=around%7C100%3A100&crop=100%3A100%3B%2A%2C%2A',
         'order': 0,
         'md5sum': 'de21c69b73b6220731a4191883338e11',
         'id': 448293,
         'photo_id': 448293,
         'uuid': 1553860184257557,
         'type': 'NORMAL'}}],
      'restaurants': [],
      'is_valid': 1,
      'share_url': 'http://www.zoma.to/r/0',
      'show_share_url': 0,
      'title': 'Live 20/20 Match Screenings',
      'description': "Catch the biggest cricket event of the year live while sippin' on these killer LIITs! Head on over to your nearest #Social to get a taste of these #SocialStumps while you cheer for your favourite team!",
      'display_time': '09:00 am - 01:35 am',
      'display_date': '29 March - 23 May',
      'is_end_time_set': 1,
      'disclaimer': 'Restaurants are solely responsible for the service; availability and quality of the events including all or any cancellations/ modifications/ complaints.',
      'event_category': 0,
      'event_category_name': '',
      'book_link': '',
      'types': [],
      'share_data': {'should_show': 0}}}],
   'opentable_support': 0,
   'is_zomato_book_res': 0,
   'mezzo_provider': 'OTHER',
   'is_book_form_web_view': 0,
   'book_form_web_view_url': '',
   'book_again_url': '',
   'thumb': 'https://b.zmtcdn.com/data/pictures/2/308322/b5221a35591a8f709a2cf34e8f4bb86b.jpg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A',
   'user_rating': {'aggregate_rating': '4.6',
    'rating_text': 'Excellent',
    'rating_color': '3F7E00',
    'votes': '13627',
    'has_fake_reviews': 0},
   'photos_url': 'https://www.zomato.com/HauzKhasSocial/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop',
   'menu_url': 'https://www.zomato.com/HauzKhasSocial/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop',
   'featured_image': 'https://b.zmtcdn.com/data/pictures/2/308322/b5221a35591a8f709a2cf34e8f4bb86b.jpg',
   'medio_provider': 1,
   'has_online_delivery': 1,
   'is_delivering_now': 1,
   'has_fake_reviews': 0,
   'include_bogo_offers': True,
   'deeplink': 'zomato://restaurant/308322',
   'order_url': 'https://www.zomato.com/HauzKhasSocial/order?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
   'order_deeplink': '',
   'is_table_reservation_supported': 1,
   'has_table_booking': 1,
   'book_url': 'https://www.zomato.com/HauzKhasSocial/book?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
   'events_url': 'https://www.zomato.com/HauzKhasSocial/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
   'establishment_types': []}},
 {'restaurant': {'R': {'res_id': 18856789},
   'apikey': 'cba15beb4c265876a9828f242b4cf41c',
   'id': '18856789',
   'name': 'AIR- An Ivory Region',
   'url': 'https://www.zomato.com/ncr/air-an-ivory-region-punjabi-bagh-new-delhi?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
   'location': {'address': '1/83, Third Floor, Club Road, West Punjabi Bagh, Punjabi Bagh, New Delhi',
    'locality': 'Punjabi Bagh',
    'city': 'New Delhi',
    'city_id': 1,
    'latitude': '28.5478090000',
    'longitude': '76.9869859000',
    'zipcode': '',
    'country_id': 1,
    'locality_verbose': 'Punjabi Bagh, New Delhi'},
   'switch_to_order_menu': 0,
   'cuisines': 'North Indian, Chinese, Continental, Asian',
   'average_cost_for_two': 1000,
   'price_range': 3,
   'currency': 'Rs.',
   'offers': [],
   'zomato_events': [{'event': {'event_id': 336644,
      'friendly_start_date': '10 April',
      'friendly_end_date': '11 April',
      'friendly_timing_str': 'Wednesday, 10th April - Thursday, 11th April',
      'start_date': '2019-04-10',
      'end_date': '2019-04-11',
      'end_time': '00:00:00',
      'start_time': '21:00:00',
      'is_active': 1,
      'date_added': '2019-04-08 12:04:49',
      'photos': [{'photo': {'url': 'https://b.zmtcdn.com/data/zomato_events/photos/46f/1c1651fcd360fe1468cfc06125b1646f_1554705305.jpg',
         'thumb_url': 'https://b.zmtcdn.com/data/zomato_events/photos/46f/1c1651fcd360fe1468cfc06125b1646f_1554705305.jpg?fit=around%7C100%3A100&crop=100%3A100%3B%2A%2C%2A',
         'order': 0,
         'md5sum': '1c1651fcd360fe1468cfc06125b1646f',
         'id': 453587,
         'photo_id': 453587,
         'uuid': 1554705309948923,
         'type': 'NORMAL'}}],
      'restaurants': [],
      'is_valid': 1,
      'share_url': 'http://www.zoma.to/r/0',
      'show_share_url': 0,
      'title': 'Dhol Bhangra Night',
      'description': 'If you want to party hard then we have the most amazing DJs lined up for you at Dhol Bhangra Night. So be there and enjoy a great time. \n\nFor Reservation: 9999122038, 9999122074',
      'display_time': '09:00 pm - 12:00 am',
      'display_date': '10 April - 11 April',
      'is_end_time_set': 1,
      'disclaimer': 'Restaurants are solely responsible for the service; availability and quality of the events including all or any cancellations/ modifications/ complaints.',
      'event_category': 0,
      'event_category_name': '',
      'book_link': '',
      'types': [{'name': 'Bollywood Night', 'color': '#6454B8'}],
      'share_data': {'should_show': 0}}}],
   'opentable_support': 0,
   'is_zomato_book_res': 1,
   'mezzo_provider': 'ZOMATO_BOOK',
   'is_book_form_web_view': 0,
   'book_form_web_view_url': '',
   'thumb': 'https://b.zmtcdn.com/data/pictures/9/18856789/df647751670debb136669d2568b94e49.jpeg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A',
   'user_rating': {'aggregate_rating': '4.1',
    'rating_text': 'Very Good',
    'rating_color': '5BA829',
    'votes': '1819',
    'has_fake_reviews': 0},
   'photos_url': 'https://www.zomato.com/ncr/air-an-ivory-region-punjabi-bagh-new-delhi/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop',
   'menu_url': 'https://www.zomato.com/ncr/air-an-ivory-region-punjabi-bagh-new-delhi/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop',
   'featured_image': 'https://b.zmtcdn.com/data/pictures/9/18856789/df647751670debb136669d2568b94e49.jpeg?output-format=webp',
   'medio_provider': '',
   'has_online_delivery': 0,
   'is_delivering_now': 0,
   'has_fake_reviews': 0,
   'include_bogo_offers': True,
   'deeplink': 'zomato://restaurant/18856789',
   'is_table_reservation_supported': 1,
   'has_table_booking': 1,
   'book_url': 'https://www.zomato.com/ncr/air-an-ivory-region-punjabi-bagh-new-delhi/book?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
   'events_url': 'https://www.zomato.com/ncr/air-an-ivory-region-punjabi-bagh-new-delhi/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
   'establishment_types': []}},
 {'restaurant': {'R': {'res_id': 307374},
   'apikey': 'cba15beb4c265876a9828f242b4cf41c',
   'id': '307374',
   'name': 'AMA Cafe',
   'url': 'https://www.zomato.com/ncr/ama-cafe-majnu-ka-tila-new-delhi?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
   'location': {'address': 'House 6, New Colony, Majnu ka Tila, New Delhi',
    'locality': 'Majnu ka Tila',
    'city': 'New Delhi',
    'city_id': 1,
    'latitude': '28.7025817618',
    'longitude': '77.2284193709',
    'zipcode': '110054',
    'country_id': 1,
    'locality_verbose': 'Majnu ka Tila, New Delhi'},
   'switch_to_order_menu': 0,
   'cuisines': 'Cafe, Juices',
   'average_cost_for_two': 450,
   'price_range': 1,
   'currency': 'Rs.',
   'offers': [],
   'opentable_support': 0,
   'is_zomato_book_res': 0,
   'mezzo_provider': 'OTHER',
   'is_book_form_web_view': 0,
   'book_form_web_view_url': '',
   'book_again_url': '',
   'thumb': 'https://b.zmtcdn.com/data/res_imagery/307374_RESTAURANT_6688d81a57b8da4bcf20d725de39a3d2.jpg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A',
   'user_rating': {'aggregate_rating': '4.4',
    'rating_text': 'Very Good',
    'rating_color': '5BA829',
    'votes': '3252',
    'has_fake_reviews': 0},
   'photos_url': 'https://www.zomato.com/ncr/ama-cafe-majnu-ka-tila-new-delhi/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop',
   'menu_url': 'https://www.zomato.com/ncr/ama-cafe-majnu-ka-tila-new-delhi/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop',
   'featured_image': 'https://b.zmtcdn.com/data/res_imagery/307374_RESTAURANT_6688d81a57b8da4bcf20d725de39a3d2.jpg?output-format=webp',
   'has_online_delivery': 0,
   'is_delivering_now': 0,
   'has_fake_reviews': 0,
   'include_bogo_offers': True,
   'deeplink': 'zomato://restaurant/307374',
   'is_table_reservation_supported': 0,
   'has_table_booking': 0,
   'events_url': 'https://www.zomato.com/ncr/ama-cafe-majnu-ka-tila-new-delhi/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
   'establishment_types': []}},
 {'restaurant': {'R': {'res_id': 18238278},
   'apikey': 'cba15beb4c265876a9828f242b4cf41c',
   'id': '18238278',
   'name': 'Tamasha',
   'url': 'https://www.zomato.com/ncr/tamasha-connaught-place-new-delhi?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
   'location': {'address': '28, Block A, Kasturba Gandhi Marg, Connaught Place, New Delhi',
    'locality': 'Connaught Place',
    'city': 'New Delhi',
    'city_id': 1,
    'latitude': '28.6296624581',
    'longitude': '77.2218600288',
    'zipcode': '110001',
    'country_id': 1,
    'locality_verbose': 'Connaught Place, New Delhi'},
   'switch_to_order_menu': 0,
   'cuisines': 'Finger Food, North Indian, Continental, Italian',
   'average_cost_for_two': 1600,
   'price_range': 3,
   'currency': 'Rs.',
   'offers': [],
   'opentable_support': 0,
   'is_zomato_book_res': 0,
   'mezzo_provider': 'OTHER',
   'is_book_form_web_view': 0,
   'book_form_web_view_url': '',
   'book_again_url': '',
   'thumb': 'https://b.zmtcdn.com/data/pictures/8/18238278/39d09a5c0215d8b12ae4742efe564a62.png?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A',
   'user_rating': {'aggregate_rating': '4.4',
    'rating_text': 'Very Good',
    'rating_color': '5BA829',
    'votes': '8112',
    'has_fake_reviews': 0},
   'photos_url': 'https://www.zomato.com/ncr/tamasha-connaught-place-new-delhi/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop',
   'menu_url': 'https://www.zomato.com/ncr/tamasha-connaught-place-new-delhi/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop',
   'featured_image': 'https://b.zmtcdn.com/data/pictures/8/18238278/39d09a5c0215d8b12ae4742efe564a62.png',
   'has_online_delivery': 0,
   'is_delivering_now': 0,
   'has_fake_reviews': 0,
   'include_bogo_offers': True,
   'deeplink': 'zomato://restaurant/18238278',
   'is_table_reservation_supported': 0,
   'has_table_booking': 0,
   'events_url': 'https://www.zomato.com/ncr/tamasha-connaught-place-new-delhi/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
   'establishment_types': []}},
 {'restaurant': {'R': {'res_id': 18268712},
   'apikey': 'cba15beb4c265876a9828f242b4cf41c',
   'id': '18268712',
   'name': "Chili's Grill & Bar",
   'url': 'https://www.zomato.com/ncr/chilis-grill-bar-sector-18-noida?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
   'location': {'address': '3rd Floor, DLF Mall Of India, Sector 18, Noida',
    'locality': 'DLF Mall of India, Sector 18,  Noida',
    'city': 'Noida',
    'city_id': 1,
    'latitude': '28.5670228841',
    'longitude': '77.3208184540',
    'zipcode': '',
    'country_id': 1,
    'locality_verbose': 'DLF Mall of India, Sector 18,  Noida, Noida'},
   'switch_to_order_menu': 0,
   'cuisines': 'Mexican, American, Italian, Burger',
   'average_cost_for_two': 1500,
   'price_range': 3,
   'currency': 'Rs.',
   'offers': [],
   'opentable_support': 0,
   'is_zomato_book_res': 0,
   'mezzo_provider': 'OTHER',
   'is_book_form_web_view': 0,
   'book_form_web_view_url': '',
   'book_again_url': '',
   'thumb': 'https://b.zmtcdn.com/data/res_imagery/4751_CHAIN_a5bff706786fbed7313bd8b8b6271ea8.jpg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A',
   'user_rating': {'aggregate_rating': '4.6',
    'rating_text': 'Excellent',
    'rating_color': '3F7E00',
    'votes': '3702',
    'has_fake_reviews': 0},
   'photos_url': 'https://www.zomato.com/ncr/chilis-grill-bar-sector-18-noida/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop',
   'menu_url': 'https://www.zomato.com/ncr/chilis-grill-bar-sector-18-noida/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop',
   'featured_image': 'https://b.zmtcdn.com/data/res_imagery/4751_CHAIN_a5bff706786fbed7313bd8b8b6271ea8.jpg',
   'medio_provider': 1,
   'has_online_delivery': 1,
   'is_delivering_now': 0,
   'has_fake_reviews': 0,
   'include_bogo_offers': True,
   'deeplink': 'zomato://restaurant/18268712',
   'is_table_reservation_supported': 1,
   'has_table_booking': 1,
   'book_url': 'https://www.zomato.com/ncr/chilis-grill-bar-sector-18-noida/book?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
   'events_url': 'https://www.zomato.com/ncr/chilis-grill-bar-sector-18-noida/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
   'establishment_types': []}},
 {'restaurant': {'R': {'res_id': 18198449},
   'apikey': 'cba15beb4c265876a9828f242b4cf41c',
   'id': '18198449',
   'name': 'Punjabi Angithi',
   'url': 'https://www.zomato.com/ncr/punjabi-angithi-paschim-vihar-new-delhi?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1',
   'location': {'address': '32-22, A-4, DDA Market, Paschim Vihar, New Delhi',
    'locality': 'Paschim Vihar',
    'city': 'New Delhi',
    'city_id': 1,
    'latitude': '28.6724925771',
    'longitude': '77.1091173962',
    'zipcode': '',
    'country_id': 1,
    'locality_verbose': 'Paschim Vihar, New Delhi'},
   'switch_to_order_menu': 0,
   'cuisines': 'North Indian, Chinese, Momos, Rolls, Fast Food',
   'average_cost_for_two': 700,
   'price_range': 2,
   'currency': 'Rs.',
   'offers': [],
   'opentable_support': 0,
   'is_zomato_book_res': 0,
   'mezzo_provider': 'OTHER',
   'is_book_form_web_view': 0,
   'book_form_web_view_url': '',
   'book_again_url': '',
   'thumb': 'https://b.zmtcdn.com/data/pictures/9/18198449/6322f562b4226c5e3c4bdfdab8afeaa1.jpg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A',
   'user_rating': {'aggregate_rating': '4.7',
    'rating_text': 'Excellent',
    'rating_color': '3F7E00',

In [51]:
restaurant_df = pd.json_normalize(json_data, 'restaurants')
restaurant_df.head()

,restaurant.R.res_id,restaurant.apikey,restaurant.id,restaurant.name,restaurant.url,restaurant.location.address,restaurant.location.locality,restaurant.location.city,restaurant.location.city_id,restaurant.location.latitude,...,restaurant.has_table_booking,restaurant.events_url,restaurant.establishment_types,restaurant.medio_provider,restaurant.order_url,restaurant.order_deeplink,restaurant.book_url,restaurant.user_rating.custom_rating_text,restaurant.user_rating.custom_rating_text_background,restaurant.user_rating.rating_tool_tip
0,18649486,cba15beb4c265876a9828f242b4cf41c,18649486,The Drunken Botanist,https://www.zomato.com/ncr/the-drunken-botanis...,"Unit 1B & 1C, Upper Ground Floor-C, Building 1...","Cyber Hub, DLF Cyber City",Gurgaon,1,28.4936741035,...,0,https://www.zomato.com/ncr/the-drunken-botanis...,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,308322,cba15beb4c265876a9828f242b4cf41c,308322,Hauz Khas Social,https://www.zomato.com/HauzKhasSocial?utm_sour...,"9-A & 12, Hauz Khas Village, New Delhi",Hauz Khas Village,New Delhi,1,28.5542935327,...,1,https://www.zomato.com/HauzKhasSocial/events#t...,[],1,https://www.zomato.com/HauzKhasSocial/order?ut...,,https://www.zomato.com/HauzKhasSocial/book?utm...,NaN,NaN,NaN
2,18856789,cba15beb4c265876a9828f242b4cf41c,18856789,AIR- An Ivory Region,https://www.zomato.com/ncr/air-an-ivory-region...,"1/83, Third Floor, Club Road, West Punjabi Bag...",Punjabi Bagh,New Delhi,1,28.5478090000,...,1,https://www.zomato.com/ncr/air-an-ivory-region...,[],,NaN,NaN,https://www.zomato.com/ncr/air-an-ivory-region...,NaN,NaN,NaN
3,307374,cba15beb4c265876a9828f242b4cf41c,307374,AMA Cafe,https://www.zomato.com/ncr/ama-cafe-majnu-ka-t...,"House 6, New Colony, Majnu ka Tila, New Delhi",Majnu ka Tila,New Delhi,1,28.7025817618,...,0,https://www.zomato.com/ncr/ama-cafe-majnu-ka-t...,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,18238278,cba15beb4c265876a9828f242b4cf41c,18238278,Tamasha,https://www.zomato.com/ncr/tamasha-connaught-p...,"28, Block A, Kasturba Gandhi Marg, Connaught P...",Connaught Place,New Delhi,1,28.6296624581,...,0,https://www.zomato.com/ncr/tamasha-connaught-p...,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [52]:
country_code_df = pd.read_excel("Country-Code.xlsx")
country_code_df

    Country Code         Country
0              1           India
1             14       Australia
2             30          Brazil
3             37          Canada
4             94       Indonesia
5            148     New Zealand
6            162     Phillipines
7            166           Qatar
8            184       Singapore
9            189    South Africa
10           191       Sri Lanka
11           208          Turkey
12           214             UAE
13           215  United Kingdom
14           216   United States

In [53]:
combined_df = pd.merge(
    restaurant_df, country_code_df, 
    how='left', left_on='restaurant.location.country_id', 
    right_on='Country Code'
)
combined_df.head()

,restaurant.R.res_id,restaurant.apikey,restaurant.id,restaurant.name,restaurant.url,restaurant.location.address,restaurant.location.locality,restaurant.location.city,restaurant.location.city_id,restaurant.location.latitude,...,restaurant.establishment_types,restaurant.medio_provider,restaurant.order_url,restaurant.order_deeplink,restaurant.book_url,restaurant.user_rating.custom_rating_text,restaurant.user_rating.custom_rating_text_background,restaurant.user_rating.rating_tool_tip,Country Code,Country
0,18649486,cba15beb4c265876a9828f242b4cf41c,18649486,The Drunken Botanist,https://www.zomato.com/ncr/the-drunken-botanis...,"Unit 1B & 1C, Upper Ground Floor-C, Building 1...","Cyber Hub, DLF Cyber City",Gurgaon,1,28.4936741035,...,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,India
1,308322,cba15beb4c265876a9828f242b4cf41c,308322,Hauz Khas Social,https://www.zomato.com/HauzKhasSocial?utm_sour...,"9-A & 12, Hauz Khas Village, New Delhi",Hauz Khas Village,New Delhi,1,28.5542935327,...,[],1,https://www.zomato.com/HauzKhasSocial/order?ut...,,https://www.zomato.com/HauzKhasSocial/book?utm...,NaN,NaN,NaN,1.0,India
2,18856789,cba15beb4c265876a9828f242b4cf41c,18856789,AIR- An Ivory Region,https://www.zomato.com/ncr/air-an-ivory-region...,"1/83, Third Floor, Club Road, West Punjabi Bag...",Punjabi Bagh,New Delhi,1,28.5478090000,...,[],,NaN,NaN,https://www.zomato.com/ncr/air-an-ivory-region...,NaN,NaN,NaN,1.0,India
3,307374,cba15beb4c265876a9828f242b4cf41c,307374,AMA Cafe,https://www.zomato.com/ncr/ama-cafe-majnu-ka-t...,"House 6, New Colony, Majnu ka Tila, New Delhi",Majnu ka Tila,New Delhi,1,28.7025817618,...,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,India
4,18238278,cba15beb4c265876a9828f242b4cf41c,18238278,Tamasha,https://www.zomato.com/ncr/tamasha-connaught-p...,"28, Block A, Kasturba Gandhi Marg, Connaught P...",Connaught Place,New Delhi,1,28.6296624581,...,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,India

In [54]:
columns_to_rename = {
    'restaurant.R.res_id': 'Restaurant Id',
    'restaurant.name': 'Restaurant Name',
    'restaurant.location.city': 'City',
    'restaurant.user_rating.votes': 'User Rating Votes',
    'restaurant.user_rating.aggregate_rating': 'User Aggregate Rating',
    'restaurant.cuisines': 'Cuisines'
}

combined_df = combined_df.rename(columns = columns_to_rename)
combined_df.head()

,Restaurant Id,restaurant.apikey,restaurant.id,Restaurant Name,restaurant.url,restaurant.location.address,restaurant.location.locality,City,restaurant.location.city_id,restaurant.location.latitude,...,restaurant.establishment_types,restaurant.medio_provider,restaurant.order_url,restaurant.order_deeplink,restaurant.book_url,restaurant.user_rating.custom_rating_text,restaurant.user_rating.custom_rating_text_background,restaurant.user_rating.rating_tool_tip,Country Code,Country
0,18649486,cba15beb4c265876a9828f242b4cf41c,18649486,The Drunken Botanist,https://www.zomato.com/ncr/the-drunken-botanis...,"Unit 1B & 1C, Upper Ground Floor-C, Building 1...","Cyber Hub, DLF Cyber City",Gurgaon,1,28.4936741035,...,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,India
1,308322,cba15beb4c265876a9828f242b4cf41c,308322,Hauz Khas Social,https://www.zomato.com/HauzKhasSocial?utm_sour...,"9-A & 12, Hauz Khas Village, New Delhi",Hauz Khas Village,New Delhi,1,28.5542935327,...,[],1,https://www.zomato.com/HauzKhasSocial/order?ut...,,https://www.zomato.com/HauzKhasSocial/book?utm...,NaN,NaN,NaN,1.0,India
2,18856789,cba15beb4c265876a9828f242b4cf41c,18856789,AIR- An Ivory Region,https://www.zomato.com/ncr/air-an-ivory-region...,"1/83, Third Floor, Club Road, West Punjabi Bag...",Punjabi Bagh,New Delhi,1,28.5478090000,...,[],,NaN,NaN,https://www.zomato.com/ncr/air-an-ivory-region...,NaN,NaN,NaN,1.0,India
3,307374,cba15beb4c265876a9828f242b4cf41c,307374,AMA Cafe,https://www.zomato.com/ncr/ama-cafe-majnu-ka-t...,"House 6, New Colony, Majnu ka Tila, New Delhi",Majnu ka Tila,New Delhi,1,28.7025817618,...,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,India
4,18238278,cba15beb4c265876a9828f242b4cf41c,18238278,Tamasha,https://www.zomato.com/ncr/tamasha-connaught-p...,"28, Block A, Kasturba Gandhi Marg, Connaught P...",Connaught Place,New Delhi,1,28.6296624581,...,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,India

In [55]:
question1_df = combined_df[[
    'Restaurant Id', 
    'Restaurant Name', 
    'Country', 
    'City', 
    'User Rating Votes', 
    'User Aggregate Rating', 
    'Cuisines'
]]

question1_df['User Aggregate Rating'] = question1_df['User Aggregate Rating'].astype('float64')

C:\Users\junke\AppData\Local\Temp\ipykernel_26076\2557604725.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  question1_df['User Aggregate Rating'] = question1_df['User Aggregate Rating'].astype('float64')

In [56]:
question1_df.head()

,Restaurant Id,Restaurant Name,Country,City,User Rating Votes,User Aggregate Rating,Cuisines
0,18649486,The Drunken Botanist,India,Gurgaon,4765,4.4,"Continental, Italian, North Indian, Chinese"
1,308322,Hauz Khas Social,India,New Delhi,13627,4.6,"Continental, American, Asian, North Indian, Ch..."
2,18856789,AIR- An Ivory Region,India,New Delhi,1819,4.1,"North Indian, Chinese, Continental, Asian"
3,307374,AMA Cafe,India,New Delhi,3252,4.4,"Cafe, Juices"
4,18238278,Tamasha,India,New Delhi,8112,4.4,"Finger Food, North Indian, Continental, Italian"

In [57]:
question1_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1300 entries, 0 to 1299
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Restaurant Id          1300 non-null   int64
 1   Restaurant Name        1300 non-null   object
 2   Country                1280 non-null   object
 3   City                   1300 non-null   object
 4   User Rating Votes      1300 non-null   object
 5   User Aggregate Rating  1300 non-null   float64
 6   Cuisines               1300 non-null   object
dtypes: float64(1), int64(1), object(5)
memory usage: 71.2+ KB

# Question 2

In [58]:
# Examine the structure of the values within the column "restaurant.zomato_events"
def check_length_list(value):
    if value is np.nan:
        return np.nan
    elif len(value) > 1:
        return value
    else:
        return np.nan

multiple_event_df = combined_df["restaurant.zomato_events"].apply(check_length_list).dropna()
multiple_event_df.iloc[0]

[{'event': {'event_id': 336889,
   'friendly_start_date': '10 April',
   'friendly_end_date': '10 April',
   'friendly_timing_str': 'Wednesday, 10th April',
   'start_date': '2019-04-10',
   'end_date': '2019-04-10',
   'end_time': '23:00:00',
   'start_time': '16:00:00',
   'is_active': 1,
   'date_added': '2019-04-08 17:58:00',
   'photos': [],
   'restaurants': [],
   'is_valid': 1,
   'share_url': 'http://www.zoma.to/r/0',
   'show_share_url': 0,
   'title': 'Cocktail Wednesday',
   'description': 'Whack your worries this Wednesday with unlimited cocktails, unlimited memories and unlimited fun only at Local.\nCall for reservations: 09599553145 \n\ndownload the android or iOs app now: http://bit.ly/2HQ2mjQ\nhttps://apple.co/2rmP7fj',
   'display_time': '04:00 pm - 11:00 pm',
   'display_date': '10 April',
   'is_end_time_set': 1,
   'disclaimer': 'Restaurants are solely responsible for the service; availability and quality of the events including all or any cancellations/ modifications/ complaints.',
   'event_category': 0,
   'event_category_name': '',
   'book_link': '',
   'types': [{'name': 'Cocktail Mixology', 'color': '#C32A6B'}],
   'share_data': {'should_show': 0}}},
 {'event': {'event_id': 336888,
   'friendly_start_date': '10 April',
   'friendly_end_date': '10 April',
   'friendly_timing_str': 'Wednesday, 10th April',
   'start_date': '2019-04-10',
   'end_date': '2019-04-10',
   'end_time': '23:55:00',
   'start_time': '20:00:00',
   'is_active': 1,
   'date_added': '2019-04-08 17:56:33',
   'photos': [],
   'restaurants': [],
   'is_valid': 1,
   'share_url': 'http://www.zoma.to/r/0',
   'show_share_url': 0,
   'title': 'Cocktail Wednesday',
   'description': 'Whack your worries this Wednesday with unlimited cocktails, unlimited memories and unlimited fun only at Local.\nCall for reservations: 09599553145 \n\ndownload the android or iOs app now: http://bit.ly/2HQ2mjQ\nhttps://apple.co/2rmP7fj',
   'display_time': '08:00 pm - 11:55 pm',
   'display_date': '10 April',
   'is_end_time_set': 1,
   'disclaimer': 'Restaurants are solely responsible for the service; availability and quality of the events including all or any cancellations/ modifications/ complaints.',
   'event_category': 0,
   'event_category_name': '',
   'book_link': '',
   'types': [{'name': 'Cocktail Mixology', 'color': '#C32A6B'}],
   'share_data': {'should_show': 0}}},
 {'event': {'event_id': 336890,
   'friendly_start_date': '10 April',
   'friendly_end_date': '10 April',
   'friendly_timing_str': 'Wednesday, 10th April',
   'start_date': '2019-04-10',
   'end_date': '2019-04-10',
   'end_time': '23:55:00',
   'start_time': '20:00:00',
   'is_active': 1,
   'date_added': '2019-04-08 17:59:18',
   'photos': [{'photo': {'url': 'https://b.zmtcdn.com/data/zomato_events/photos/193/bed72acb4c93b8affeba209ccad08193_1554726578.jpg',
      'thumb_url': 'https://b.zmtcdn.com/data/zomato_events/photos/193/bed72acb4c93b8affeba209ccad08193_1554726578.jpg?fit=around%7C100%3A100&crop=100%3A100%3B%2A%2C%2A',
      'order': 0,
      'md5sum': 'bed72acb4c93b8affeba209ccad08193',
      'id': 453897,
      'photo_id': 453897,
      'uuid': 1554726575991324,
      'type': 'NORMAL'}}],
   'restaurants': [],
   'is_valid': 1,
   'share_url': 'http://www.zoma.to/r/0',
   'show_share_url': 0,
   'title': 'Cocktail Wednesday',
   'description': 'Whack your worries this Wednesday with unlimited cocktails, unlimited memories and unlimited fun only at Local.\nCall for reservations: 09599553145 \n\ndownload the android or iOs app now: http://bit.ly/2HQ2mjQ\nhttps://apple.co/2rmP7fj',
   'display_time': '08:00 pm - 11:55 pm',
   'display_date': '10 April',
   'is_end_time_set': 1,
   'disclaimer': 'Restaurants are solely responsible for the service; availability and quality of the events including all or any cancellations/ modifications/ complaints.',
   'event_category': 0,
   'event_category_name': '',
   'book_link': '',
   'types': [{'name': 'Cocktail Mixology', 'color': '#C32A6B'}],
   'share_data': {'should_show': 0}}},
 {'event': {'event_id': 336894,
   'friendly_start_date': '12 April',
   'friendly_end_date': '12 April',
   'friendly_timing_str': 'Friday, 12th April',
   'start_date': '2019-04-12',
   'end_date': '2019-04-12',
   'end_time': '23:00:00',
   'start_time': '20:00:00',
   'is_active': 1,
   'date_added': '2019-04-08 18:05:01',
   'photos': [{'photo': {'url': 'https://b.zmtcdn.com/data/zomato_events/photos/f6c/0aea33156c313eef2343ac6f0e0a5f6c_1554726952.jpg',
      'thumb_url': 'https://b.zmtcdn.com/data/zomato_events/photos/f6c/0aea33156c313eef2343ac6f0e0a5f6c_1554726952.jpg?fit=around%7C100%3A100&crop=100%3A100%3B%2A%2C%2A',
      'order': 0,
      'md5sum': '0aea33156c313eef2343ac6f0e0a5f6c',
      'id': 453908,
      'photo_id': 453908,
      'uuid': 1554726949554829,
      'type': 'NORMAL'}}],
   'restaurants': [],
   'is_valid': 1,
   'share_url': 'http://www.zoma.to/r/0',
   'show_share_url': 0,
   'title': 'Hip Hop Friday',
   'description': 'Why be a bore on a Friday when we have organized Hip Hop Night for you #partyfreaks at Local CP. Right? So start gathering your buddies and head towards us as this is going to be great.\n\nFor Reservation:- 9599553145',
   'display_time': '08:00 pm - 11:00 pm',
   'display_date': '12 April',
   'is_end_time_set': 1,
   'disclaimer': 'Restaurants are solely responsible for the service; availability and quality of the events including all or any cancellations/ modifications/ complaints.',
   'event_category': 0,
   'event_category_name': '',
   'book_link': '',
   'types': [{'name': 'Live DJ', 'color': '#6454B8'}],
   'share_data': {'should_show': 0}}},
 {'event': {'event_id': 336903,
   'friendly_start_date': '13 April',
   'friendly_end_date': '13 April',
   'friendly_timing_str': 'Saturday, 13th April',
   'start_date': '2019-04-13',
   'end_date': '2019-04-13',
   'end_time': '23:55:00',
   'start_time': '20:00:00',
   'is_active': 1,
   'date_added': '2019-04-08 18:20:22',
   'photos': [{'photo': {'url': 'https://b.zmtcdn.com/data/zomato_events/photos/5ee/165894b7ce0bfd2812796a3f8c6f15ee_1554728236.jpg',
      'thumb_url': 'https://b.zmtcdn.com/data/zomato_events/photos/5ee/165894b7ce0bfd2812796a3f8c6f15ee_1554728236.jpg?fit=around%7C100%3A100&crop=100%3A100%3B%2A%2C%2A',
      'order': 0,
      'md5sum': '165894b7ce0bfd2812796a3f8c6f15ee',
      'id': 453924,
      'photo_id': 453924,
      'uuid': 1554728232603922,
      'type': 'NORMAL'}}],
   'restaurants': [],
   'is_valid': 1,
   'share_url': 'http://www.zoma.to/r/0',
   'show_share_url': 0,
   'title': 'Urban Saturday',
   'description': 'Reenergize yourself by attending with your buddies Urban Saturday on 6th April at Local CP. Get ready for it in advance as Saurabh is assuring head-bobbing craziness.\n\nCall for reservations: 09599553145 \ndownload the android or iOs app now: http://bit.ly/2HQ2mjQ\nhttps://apple.co/2rmP7fj',
   'display_time': '08:00 pm - 11:55 pm',
   'display_date': '13 April',
   'is_end_time_set': 1,
   'disclaimer': 'Restaurants are solely responsible for the service; availability and quality of the events including all or any cancellations/ modifications/ complaints.',
   'event_category': 0,
   'event_category_name': '',
   'book_link': '',
   'types': [{'name': 'Solo Performance', 'color': '#6454B8'}],
   'share_data': {'should_show': 0}}}]

In [59]:
# Expand event column vertically
explode_events_restaurant_df = combined_df.explode("restaurant.zomato_events")

print(len(explode_events_restaurant_df))

1400

In [60]:
# Unpack the dictionaries 
expnd_events_restaurant_df = pd.json_normalize(
    explode_events_restaurant_df['restaurant.zomato_events']
)
print(len(expnd_events_restaurant_df))

1400

In [61]:
merged_events_df = expnd_events_restaurant_df.join(explode_events_restaurant_df)
merged_events_df.head()

,event.event_id,event.friendly_start_date,event.friendly_end_date,event.friendly_timing_str,event.start_date,event.end_date,event.end_time,event.start_time,event.is_active,event.date_added,...,restaurant.establishment_types,restaurant.medio_provider,restaurant.order_url,restaurant.order_deeplink,restaurant.book_url,restaurant.user_rating.custom_rating_text,restaurant.user_rating.custom_rating_text_background,restaurant.user_rating.rating_tool_tip,Country Code,Country
0,322331.0,06 March,28 August,"Wednesday, 6th March - Wednesday, 28th August",2019-03-06,2019-08-28,23:59:59,20:00:00,1.0,2019-03-06 11:41:21,...,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,India
1,332812.0,29 March,23 May,"Friday, 29th March - Thursday, 23rd May",2019-03-29,2019-05-23,01:35:00,09:00:00,1.0,2019-03-29 17:19:54,...,[],1,https://www.zomato.com/HauzKhasSocial/order?ut...,,https://www.zomato.com/HauzKhasSocial/book?utm...,NaN,NaN,NaN,1.0,India
2,336644.0,10 April,11 April,"Wednesday, 10th April - Thursday, 11th April",2019-04-10,2019-04-11,00:00:00,21:00:00,1.0,2019-04-08 12:04:49,...,[],,NaN,NaN,https://www.zomato.com/ncr/air-an-ivory-region...,NaN,NaN,NaN,1.0,India
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,India
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,India

In [62]:
merged_events_df = merged_events_df.rename(columns={"restaurant.zomato_events": "zomato_events"})

In [63]:

merged_events_df['event.start_date'] = pd.to_datetime(merged_events_df['event.start_date'])
merged_events_df['event.end_date'] = pd.to_datetime(merged_events_df['event.end_date'])

In [64]:
condition_startdate = (merged_events_df['event.start_date'].dt.year < 2019) | \
    ((merged_events_df['event.start_date'].dt.year == 2019) & (merged_events_df['event.start_date'].dt.month <= 4))


condition_enddate = (merged_events_df['event.end_date'].dt.year > 2019) | \
    ((merged_events_df['event.end_date'].dt.year == 2019) & (merged_events_df['event.end_date'].dt.month >= 4))

# Apply conditions
filtered_event_df = merged_events_df[condition_enddate & condition_startdate]
filtered_event_df.head()

,event.event_id,event.friendly_start_date,event.friendly_end_date,event.friendly_timing_str,event.start_date,event.end_date,event.end_time,event.start_time,event.is_active,event.date_added,...,restaurant.establishment_types,restaurant.medio_provider,restaurant.order_url,restaurant.order_deeplink,restaurant.book_url,restaurant.user_rating.custom_rating_text,restaurant.user_rating.custom_rating_text_background,restaurant.user_rating.rating_tool_tip,Country Code,Country
0,322331.0,06 March,28 August,"Wednesday, 6th March - Wednesday, 28th August",2019-03-06,2019-08-28,23:59:59,20:00:00,1.0,2019-03-06 11:41:21,...,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,India
1,332812.0,29 March,23 May,"Friday, 29th March - Thursday, 23rd May",2019-03-29,2019-05-23,01:35:00,09:00:00,1.0,2019-03-29 17:19:54,...,[],1,https://www.zomato.com/HauzKhasSocial/order?ut...,,https://www.zomato.com/HauzKhasSocial/book?utm...,NaN,NaN,NaN,1.0,India
2,336644.0,10 April,11 April,"Wednesday, 10th April - Thursday, 11th April",2019-04-10,2019-04-11,00:00:00,21:00:00,1.0,2019-04-08 12:04:49,...,[],,NaN,NaN,https://www.zomato.com/ncr/air-an-ivory-region...,NaN,NaN,NaN,1.0,India
7,336889.0,10 April,10 April,"Wednesday, 10th April",2019-04-10,2019-04-10,23:00:00,16:00:00,1.0,2019-04-08 17:58:00,...,[],1,NaN,NaN,NaN,NaN,NaN,NaN,1.0,India
7,336889.0,10 April,10 April,"Wednesday, 10th April",2019-04-10,2019-04-10,23:00:00,16:00:00,1.0,2019-04-08 17:58:00,...,[],1,NaN,NaN,NaN,NaN,NaN,NaN,1.0,India

In [65]:
print(len(filtered_event_df))

229

In [66]:
examine_photo_df = filtered_event_df["event.photos"].apply(check_length_list).dropna()
examine_photo_df.iloc[0]

[{'photo': {'url': 'https://b.zmtcdn.com/data/zomato_events/photos/647/21460fdc477d489aa14b5737ad8b4647_1545986849.jpg',
   'thumb_url': 'https://b.zmtcdn.com/data/zomato_events/photos/647/21460fdc477d489aa14b5737ad8b4647_1545986849.jpg?fit=around%7C100%3A100&crop=100%3A100%3B%2A%2C%2A',
   'order': 0,
   'md5sum': '21460fdc477d489aa14b5737ad8b4647',
   'id': 395646,
   'photo_id': 395646,
   'uuid': 15459868486638,
   'type': 'FEATURED'}},
 {'photo': {'url': 'https://b.zmtcdn.com/data/zomato_events/photos/9d8/64650c048db51b793f4cb1ba5b72a9d8_1545986850.jpg',
   'thumb_url': 'https://b.zmtcdn.com/data/zomato_events/photos/9d8/64650c048db51b793f4cb1ba5b72a9d8_1545986850.jpg?fit=around%7C100%3A100&crop=100%3A100%3B%2A%2C%2A',
   'order': 1,
   'md5sum': '64650c048db51b793f4cb1ba5b72a9d8',
   'id': 395647,
   'photo_id': 395647,
   'uuid': 15459868485387,
   'type': 'NORMAL'}},
 {'photo': {'url': 'https://b.zmtcdn.com/data/zomato_events/photos/c67/5e7cc582f8d1c247402f7e63df920c67_1546020375.jpg',
   'thumb_url': 'https://b.zmtcdn.com/data/zomato_events/photos/c67/5e7cc582f8d1c247402f7e63df920c67_1546020375.jpg?fit=around%7C100%3A100&crop=100%3A100%3B%2A%2C%2A',
   'order': 2,
   'md5sum': '5e7cc582f8d1c247402f7e63df920c67',
   'id': 396086,
   'photo_id': 396086,
   'uuid': 15460203754108,
   'type': 'NORMAL'}}]

In [67]:
# Expand event column vertically
explode_photos_df = filtered_event_df.explode("event.photos")

len(explode_photos_df)

292

In [68]:
explode_photos_df.head()

,event.event_id,event.friendly_start_date,event.friendly_end_date,event.friendly_timing_str,event.start_date,event.end_date,event.end_time,event.start_time,event.is_active,event.date_added,...,restaurant.establishment_types,restaurant.medio_provider,restaurant.order_url,restaurant.order_deeplink,restaurant.book_url,restaurant.user_rating.custom_rating_text,restaurant.user_rating.custom_rating_text_background,restaurant.user_rating.rating_tool_tip,Country Code,Country
0,322331.0,06 March,28 August,"Wednesday, 6th March - Wednesday, 28th August",2019-03-06,2019-08-28,23:59:59,20:00:00,1.0,2019-03-06 11:41:21,...,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,India
1,332812.0,29 March,23 May,"Friday, 29th March - Thursday, 23rd May",2019-03-29,2019-05-23,01:35:00,09:00:00,1.0,2019-03-29 17:19:54,...,[],1,https://www.zomato.com/HauzKhasSocial/order?ut...,,https://www.zomato.com/HauzKhasSocial/book?utm...,NaN,NaN,NaN,1.0,India
2,336644.0,10 April,11 April,"Wednesday, 10th April - Thursday, 11th April",2019-04-10,2019-04-11,00:00:00,21:00:00,1.0,2019-04-08 12:04:49,...,[],,NaN,NaN,https://www.zomato.com/ncr/air-an-ivory-region...,NaN,NaN,NaN,1.0,India
7,336889.0,10 April,10 April,"Wednesday, 10th April",2019-04-10,2019-04-10,23:00:00,16:00:00,1.0,2019-04-08 17:58:00,...,[],1,NaN,NaN,NaN,NaN,NaN,NaN,1.0,India
7,336889.0,10 April,10 April,"Wednesday, 10th April",2019-04-10,2019-04-10,23:00:00,16:00:00,1.0,2019-04-08 17:58:00,...,[],1,NaN,NaN,NaN,NaN,NaN,NaN,1.0,India

In [69]:

# Unpack the dictionaries 
expnd_photos_restaurant_df = pd.json_normalize(
    explode_photos_df['event.photos']
)

len(expnd_photos_restaurant_df)

292

In [70]:
merged_photos_df = explode_photos_df.join(expnd_photos_restaurant_df)
len(merged_photos_df)

292

In [71]:
merged_photos_df.head()

,event.event_id,event.friendly_start_date,event.friendly_end_date,event.friendly_timing_str,event.start_date,event.end_date,event.end_time,event.start_time,event.is_active,event.date_added,...,Country Code,Country,photo.url,photo.thumb_url,photo.order,photo.md5sum,photo.id,photo.photo_id,photo.uuid,photo.type
0,322331.0,06 March,28 August,"Wednesday, 6th March - Wednesday, 28th August",2019-03-06,2019-08-28,23:59:59,20:00:00,1.0,2019-03-06 11:41:21,...,1.0,India,https://b.zmtcdn.com/data/zomato_events/photos...,https://b.zmtcdn.com/data/zomato_events/photos...,0.0,ac34cf3c271c9052e9d248c243df65a1,434436.0,434436.0,5.269523e+10,FEATURED
1,332812.0,29 March,23 May,"Friday, 29th March - Thursday, 23rd May",2019-03-29,2019-05-23,01:35:00,09:00:00,1.0,2019-03-29 17:19:54,...,1.0,India,https://b.zmtcdn.com/data/zomato_events/photos...,https://b.zmtcdn.com/data/zomato_events/photos...,0.0,de21c69b73b6220731a4191883338e11,448293.0,448293.0,1.553860e+15,NORMAL
2,336644.0,10 April,11 April,"Wednesday, 10th April - Thursday, 11th April",2019-04-10,2019-04-11,00:00:00,21:00:00,1.0,2019-04-08 12:04:49,...,1.0,India,https://b.zmtcdn.com/data/zomato_events/photos...,https://b.zmtcdn.com/data/zomato_events/photos...,0.0,1c1651fcd360fe1468cfc06125b1646f,453587.0,453587.0,1.554705e+15,NORMAL
7,336889.0,10 April,10 April,"Wednesday, 10th April",2019-04-10,2019-04-10,23:00:00,16:00:00,1.0,2019-04-08 17:58:00,...,1.0,India,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,336889.0,10 April,10 April,"Wednesday, 10th April",2019-04-10,2019-04-10,23:00:00,16:00:00,1.0,2019-04-08 17:58:00,...,1.0,India,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [72]:
final_columns = [
    "event.event_id", "Restaurant Id", "Restaurant Name", 
    "restaurant.photos_url", "event.title", "event.start_date", "event.end_date"
]
final_events_df = merged_photos_df[final_columns]

columns_to_rename = {
    "event.event_id": "Event Id", 
    "restaurant.photos_url": "Photo URL",
    "event.title": "Event Title", 
    "event.start_date": "Event Start Date",
    "event.end_date": "Event End Date"
}

# Rename columns for readability
question2_df = final_events_df.rename(columns=columns_to_rename)

question2_df.head()

,Event Id,Restaurant Id,Restaurant Name,Photo URL,Event Title,Event Start Date,Event End Date
0,322331.0,18649486.0,The Drunken Botanist,https://www.zomato.com/ncr/the-drunken-botanis...,BackToBasic Wednesdays !!\n\n\n,2019-03-06,2019-08-28
1,332812.0,308322.0,Hauz Khas Social,https://www.zomato.com/HauzKhasSocial/photos?u...,Live 20/20 Match Screenings,2019-03-29,2019-05-23
2,336644.0,18856789.0,AIR- An Ivory Region,https://www.zomato.com/ncr/air-an-ivory-region...,Dhol Bhangra Night,2019-04-10,2019-04-11
7,336889.0,18382360.0,Local,https://www.zomato.com/ncr/local-connaught-pla...,Cocktail Wednesday,2019-04-10,2019-04-10
7,336889.0,18382360.0,Local,https://www.zomato.com/ncr/local-connaught-pla...,Cocktail Wednesday,2019-04-10,2019-04-10

# Question 3

In [73]:
filtered_df = restaurant_df[
    restaurant_df['restaurant.user_rating.rating_text'].isin(
        ['Excellent', 'Very Good', 'Good', 'Average', 'Poor']
    )
]
filtered_df.head()

,restaurant.R.res_id,restaurant.apikey,restaurant.id,restaurant.name,restaurant.url,restaurant.location.address,restaurant.location.locality,restaurant.location.city,restaurant.location.city_id,restaurant.location.latitude,...,restaurant.has_table_booking,restaurant.events_url,restaurant.establishment_types,restaurant.medio_provider,restaurant.order_url,restaurant.order_deeplink,restaurant.book_url,restaurant.user_rating.custom_rating_text,restaurant.user_rating.custom_rating_text_background,restaurant.user_rating.rating_tool_tip
0,18649486,cba15beb4c265876a9828f242b4cf41c,18649486,The Drunken Botanist,https://www.zomato.com/ncr/the-drunken-botanis...,"Unit 1B & 1C, Upper Ground Floor-C, Building 1...","Cyber Hub, DLF Cyber City",Gurgaon,1,28.4936741035,...,0,https://www.zomato.com/ncr/the-drunken-botanis...,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,308322,cba15beb4c265876a9828f242b4cf41c,308322,Hauz Khas Social,https://www.zomato.com/HauzKhasSocial?utm_sour...,"9-A & 12, Hauz Khas Village, New Delhi",Hauz Khas Village,New Delhi,1,28.5542935327,...,1,https://www.zomato.com/HauzKhasSocial/events#t...,[],1,https://www.zomato.com/HauzKhasSocial/order?ut...,,https://www.zomato.com/HauzKhasSocial/book?utm...,NaN,NaN,NaN
2,18856789,cba15beb4c265876a9828f242b4cf41c,18856789,AIR- An Ivory Region,https://www.zomato.com/ncr/air-an-ivory-region...,"1/83, Third Floor, Club Road, West Punjabi Bag...",Punjabi Bagh,New Delhi,1,28.5478090000,...,1,https://www.zomato.com/ncr/air-an-ivory-region...,[],,NaN,NaN,https://www.zomato.com/ncr/air-an-ivory-region...,NaN,NaN,NaN
3,307374,cba15beb4c265876a9828f242b4cf41c,307374,AMA Cafe,https://www.zomato.com/ncr/ama-cafe-majnu-ka-t...,"House 6, New Colony, Majnu ka Tila, New Delhi",Majnu ka Tila,New Delhi,1,28.7025817618,...,0,https://www.zomato.com/ncr/ama-cafe-majnu-ka-t...,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,18238278,cba15beb4c265876a9828f242b4cf41c,18238278,Tamasha,https://www.zomato.com/ncr/tamasha-connaught-p...,"28, Block A, Kasturba Gandhi Marg, Connaught P...",Connaught Place,New Delhi,1,28.6296624581,...,0,https://www.zomato.com/ncr/tamasha-connaught-p...,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [74]:
filtered_df['restaurant.user_rating.aggregate_rating'] = filtered_df['restaurant.user_rating.aggregate_rating'].apply(pd.to_numeric)
filtered_df = filtered_df.rename(columns={"restaurant.user_rating.rating_text":"Rating Text"})

C:\Users\junke\AppData\Local\Temp\ipykernel_26076\1350759950.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df['restaurant.user_rating.aggregate_rating'] = filtered_df['restaurant.user_rating.aggregate_rating'].apply(pd.to_numeric)

In [75]:
rating_threshold = filtered_df.groupby(
    'Rating Text', as_index=False)['restaurant.user_rating.aggregate_rating'].agg(['min', 'max'])

rating_threshold

  Rating Text  min  max
0     Average  2.5  3.4
1   Excellent  4.5  4.9
2        Good  3.5  3.9
3        Poor  2.2  2.2
4   Very Good  4.0  4.4